### ISSUE TITLE
The syntax of the command is incorrect.

### ISSUE THREAD

**Issue by rllyryan** [salesforce/warp-drive#40]
Dear WarpDrive team,

I have arrived with another issue regarding the testing of installation of WarpDrive via **pip rl-warp-drive**.

**I also git-cloned the repository onto my local machine.**

**I am running on Windows 11, Python 3.8.10, Pytorch 1.9.0+cu111**

Running the `python warp_drive/utils/run_unittests.py` command in Visual Studios Code gives the error:
```
The syntax of the command is incorrect.
Traceback (most recent call last):
  File "warp_drive/utils/run_unittests.py", line 21, in <module>
    cuda_function_manager.compile(main_file, cubin_file)
  File "C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\warp_drive\managers\function_manager.py", line 262, in _compile
    raise Exception("make bin file failed ... ")
Exception: make bin file failed ...
```
On the other hand running the `python .\run_trainer_tests.py` command gives the error:
```
=============================================================================== FAILURES =============================================================================== 
_______________________________________________________________ MyTestCase.test_tag_continuous_training ________________________________________________________________ 

self = <tests.wd_training.test_env_training.MyTestCase testMethod=test_tag_continuous_training>

    def test_tag_continuous_training(self):
        run_config = self.get_config("tag_continuous")
        try:
            run_config["env"]["num_taggers"] = 2
            run_config["env"]["num_runners"] = 10
>           launch_process(
                setup_trainer_and_train,
                kwargs={"run_configuration": run_config, "verbose": False},
            )

C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py:66:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _  

func = <function setup_trainer_and_train at 0x00000294A9BB6700>
kwargs = {'run_configuration': {'env': {'edge_hit_penalty': 0.0, 'end_of_game_reward_for_runner': 1.0, 'episode_length': 500, '.../tmp', 'metrics_log_freq': 100, 'model_params_save_freq': 5000, 'name': 'tag_continuous', ...}, ...}, 'verbose': False}

    def launch_process(func, kwargs):
        """
        Run a Python function on a separate process.
        """
        p = ProcessWrapper(target=func, kwargs=kwargs)
        p.start()
        p.join()
        if p.exception:
>           raise p.exception
E           Exception: make bin file failed ...

C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py:28: Exception
------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------- 
The syntax of the command is incorrect.
------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------- 
C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\gym\utils\seeding.py:41: DeprecationWarning: WARN: Function `rng.rand(*size)` is marked as deprecated and will be removed in the future. Please use `Generator.random(size)` instead.
  deprecation(
ERROR:root:make bin file failed ...
________________________________________________________________ MyTestCase.test_tag_gridworld_training ________________________________________________________________ 

self = <tests.wd_training.test_env_training.MyTestCase testMethod=test_tag_gridworld_training>

    def test_tag_gridworld_training(self):
        run_config = self.get_config("tag_gridworld")
        try:
>           launch_process(
                setup_trainer_and_train,
                kwargs={"run_configuration": run_config, "verbose": False},
        p.join()
        if p.exception:
>           raise p.exception
E           Exception: make bin file failed ...

C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py:28: Exception
------------------------------------------------------------------------- Captured stdout call ------------------------------------------------------------------------- The syntax of the command is incorrect.
------------------------------------------------------------------------- Captured stderr call ------------------------------------------------------------------------- 
ERROR:root:make bin file failed ...
=========================================================================== warnings summary =========================================================================== 
..\..\..\..\..\..\AppData\Local\Programs\Python\Python38\lib\site-packages\pycuda\compyte\dtypes.py:120
  C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\pycuda\compyte\dtypes.py:120: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
  Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
    reg.get_or_register_dtype("bool", np.bool)

AppData/Local/Programs/Python/Python38/lib/site-packages/tests/wd_training/test_env_training.py::MyTestCase::test_tag_gridworld_training_with_multiple_devices
  C:\Users\ryanl\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py:75: UserWarning: Only single GPU is detected, we skip trainer test for multiple devices
    warnings.warn("Only single GPU is detected, we skip trainer test for multiple devices")

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================================================= short test summary info ======================================================================== 
FAILED ..\..\..\..\..\..\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py::MyTestCase::test_tag_continuous_training - E...FAILED ..\..\..\..\..\..\AppData\Local\Programs\Python\Python38\lib\site-packages\tests\wd_training\test_env_training.py::MyTestCase::test_tag_gridworld_training - Ex...=============================================================== 2 failed, 1 passed, 2 warnings in 11.18s =============================================================== 
```
I was not able to deduce the issue behind this error.

Also could I find out whether it is better to run it in a LINUX environment or a WINDOWS environment?

I appreciate any help I can get on this!

Thank you :)

**Comment by Emerald01** [comment]
Definitely Linux. For GPU computation, I do not think many people will try on Windows, it will incur a lot of troubles debugging drivers and libraries incompabilitility. And what you met is for sure one of them.
